### ISSUE TITLE
Is it possible to update only the files in the archive？

### ISSUE THREAD

**Issue by lisenz** [FlukeFan/ZipDeploy#2]
Hi， @FlukeFan 

I have a new problem.

Sometimes I only need to publish some specified files, and I don't need to update all files, but ZipDeloy will delete all files in the root directory, and then decompress and use the files in publish.zip.

e.g:
My program has a total of 10 .dll files, which are 1.dll, 2.dll...10.dll, and then I only need to update 2.dll, 3.dll, so I will 2.dll and 3.dll file is put into publish.zip, but ZipDeloy will delete all the files, and finally only 2.dll and 3.dll are left.

But I want ZipDeloy to update only replace 2.dll and 3.dll files.

**Comment by FlukeFan** [comment]
So I think it should already do that.  After it unzips the files (the first time), it should create a file named "zipDeployFileHashes.txt".  It should then only replace the files that have changed hash.

You still need to supply all the files in the publish.zip though.  Without the complete file list, it won't know what should be deleted.

**Comment by lisenz** [comment]
I think may be ZipDeploy can just delete the list of files provided in publish.zip?

**Comment by lisenz** [comment]
I think may be ZipDeploy can just delete the list of files provided in publish.zip?

Because the files released by each update are not always the same.

**Comment by FlukeFan** [comment]
I'm not sure I understand.

If the existing app has dlls:  1.dll, 2.dll
The uploaded zip has: 1.dll, 3.dll


ZipDeploy will update 1.dll (if it has changed), create 3.dll, and delete 2.dll.

If only 1.dll was supplied, how would it know when/if to delete 2.dll?

**Comment by lisenz** [comment]
If the existing app has dlls: 1.dll, 2.dll
The uploaded zip has: 1.dll, 3.dll

I hope ZipDeploy will update 1.dll (if it has changed), create 3.dll, and keep the 2.dll.

Because the 2.dll file is not in publish.zip, it means that 2.dll does not need to be updated (which is what I think).

**Comment by FlukeFan** [comment]
The intention is to zip up a complete publish folder, zip it up, and make the server mirror what is in the zip file.

In your example, if 2.dll is obsolete (no longer in the published output), then it should (IMO) be deleted.  Otherwise, over time, many extra files (not just assemblies, but wwwroot files too) will be left on the server (that shouldn't be there).

Leaving 'old' files can also cause problems for applications that dynamically load assemblies (plugins, for example), where it searches for all available assemblies at runtime.

**Comment by lisenz** [comment]
Oh， I got it.
Thank you for your reply,
now I understand. :-)
